source 'https://rubygems.org'

# gem "jekyll-remote-theme"
gem "jekyll-sitemap"
# gem "jekyll-tidy", "~> 0.2.2"
gem "json"
gem "just-the-docs"
gem "kramdown"
gem "rouge"

# Automatically building is disabled because this guy won't install
# gem "github-pages", group: :jekyll_plugins

# jekyll-gist requires github-pages above
# https://gist.github.com/benbalter/5555251#gistcomment-2242186
# gem "jekyll-gist"
