import { EventEmitter, ListenerFn } from 'eventemitter3';
import { JsonRpcRequest } from './jsonrpc2';
import { MetapageShared } from './Shared';
import { JsonRpcMethodsFromParent, MetaframeDefinitionV6, MetaframeId, MetaframeInputMap, MetaframePipeId, MetapageId, VersionsMetaframe } from './v0_4';
import { MetapageEvents } from './v0_4/events';
export declare class MetapageIFrameRpcClient extends EventEmitter<JsonRpcMethodsFromParent | MetapageEvents> {
    iframe: Promise<HTMLIFrameElement>;
    _iframe: HTMLIFrameElement;
    id: MetaframeId;
    version: VersionsMetaframe | undefined;
    url: string;
    _color: string;
    _consoleBackgroundColor: string;
    inputs: MetaframeInputMap;
    outputs: MetaframeInputMap;
    _disposables: (() => void)[];
    _rpcListeners: ((r: JsonRpcRequest<any>) => void)[];
    _loaded: boolean;
    _onLoaded: (() => void)[];
    _parentId: MetapageId;
    _debug: boolean;
    _sendInputsAfterRegistration: boolean;
    _definition: MetaframeDefinitionV6 | undefined;
    _plugin: boolean;
    _metapage: MetapageShared;
    constructor(metapage: MetapageShared, url: string, iframeId: MetaframeId, parentId: MetapageId, consoleBackgroundColor: string, debug?: boolean);
    addListenerReturnDisposer(event: JsonRpcMethodsFromParent | MetapageEvents, listener: ListenerFn<any[]>): () => void;
    setPlugin(): MetapageIFrameRpcClient;
    setMetapage(metapage: MetapageShared): MetapageIFrameRpcClient;
    hasPermissionsState(): boolean;
    hasPermissionsDefinition(): boolean;
    getDefinitionUrl(): string;
    getDefinition(): Promise<MetaframeDefinitionV6 | undefined>;
    setInput(name: MetaframePipeId, inputBlob: any): void;
    _cachedEventInputsUpdate: {
        iframeId: string | undefined;
        inputs: MetaframeInputMap | undefined;
    };
    setInputs(maybeNewInputs: MetaframeInputMap): MetapageIFrameRpcClient;
    setOutput(pipeId: MetaframePipeId, updateBlob: any): void;
    _cachedEventOutputsUpdate: {
        iframeId: null;
        inputs: null;
    };
    setOutputs(maybeNewOutputs: MetaframeInputMap): void;
    onInputs(f: (m: MetaframeInputMap) => void): () => void;
    onInput(pipeName: MetaframePipeId, f: (_: any) => void): () => void;
    onOutputs(f: (m: MetaframeInputMap) => void): () => void;
    onOutput(pipeName: MetaframePipeId, f: (_: any) => void): () => void;
    isDisposed(): boolean;
    dispose(): void;
    register(): void;
    registered(version: VersionsMetaframe): void;
    sendInputs(inputs: MetaframeInputMap): Promise<void>;
    sendRpc(method: string, params: any): void;
    ack(message: any): void;
    log(o: any): void;
    logInternal(o: any): void;
    sendRpcInternal(method: string, params: any): void;
    _bufferMessages: any[] | undefined;
    _bufferTimeout: number | undefined;
    sendOrBufferPostMessage(message: any): void;
}
//# sourceMappingURL=MetapageIFrameRpcClient.d.ts.map