set shell               := ["bash", "-c"]
set dotenv-load         := true
set export              := true
APP_FQDN                := env_var_or_default("APP_FQDN", "localhost")
APP_PORT                := env_var_or_default("APP_PORT", "4430")
DENO_DEPLOY_TOKEN       := env_var_or_default("DENO_DEPLOY_TOKEN", "")
# minimal formatting, bold is very useful
bold                               := '\033[1m'
normal                             := '\033[0m'
green                              := "\\e[32m"
yellow                             := "\\e[33m"
blue                               := "\\e[34m"
magenta                            := "\\e[35m"
grey                               := "\\e[90m"

@_help:
    just --list --unsorted
    echo -e "APP_FQDN={{APP_FQDN}}"

# Run the server in development mode
@dev +args="": clean _mkcert _build_local_module open
  deno task start

open:
  deno run --allow-all https://deno.land/x/metapages@v0.0.27/exec/open_url.ts 'https://metapages.github.io/load-page-when-available/?url=https://{{APP_FQDN}}:{{APP_PORT}}'

deploy:
  #!/usr/bin/env bash
  set -euo pipefail
  rm -rf deploy
  mkdir -p deploy
  cp -rL src deploy/
  cp -r deno.json deploy/
  cd deploy
  # deploy deploy is on an older version of deno which does not support 
  # the "sloppy-imports" flag
  # So jump through some hoops to convert the imports
  find src/lib -type f -name '*.ts' -exec sd -s ".js'" ".ts'" {} +
  find src/lib -type f -name '*.ts' -exec sd -s '.js"' '.ts"' {} +
  deno task build
  deno deploy --prod

# Delete all cached and generated files, and docker volumes
@clean:
  rm -rf .certs
  rm -rf deploy
  rm -rf src/_fresh
  echo -e "✅ Cleaned worker"

test: _build_local_module _mkcert
  APP_PORT=8762 deno run -A --unsafely-ignore-certificate-errors test/src/run-tests-in-astral.ts

build: _build_local_module
  deno task build

@check:
  deno check src/main.ts
  echo "✅ worker typescript compilation"

@_build_local_module:
  just ../lib/build

# DEV: generate TLS certs for HTTPS over localhost https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/
@_mkcert:
  rm -rf .certs
  mkdir -p .certs
  mkcert -cert-file .certs/local-cert.pem -key-file .certs/local-key.pem localhost metapage-npm.dev 127.0.0.1
