source 'https://rubygems.org'

gem "json"
gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "minima"
gem "kramdown"
gem "rouge"
gem "jekyll-watch"
# gem "github-pages", group: :jekyll_plugins