# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Deno deploy worker

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - "fix-development"

jobs:
  deno-deploy-worker:
    # Can switch to ubuntu-latest but self-hosted is safer and faster
    name: Deno deploy worker
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: deno deploy worker
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: just app/worker/deploy

